version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=KHV
      - MONGO_INITDB_ROOT_PASSWORD=SomeStupidPassword
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  firewall-api:
    build:
      context: ./firewall_API
      dockerfile: dockerfile
    container_name: firewall-api
    ports:
      - "5000:5000"
    environment:
      - DB_URI=mongodb://admin:SomeStupidPassword@mongodb:27017
      - CORS_ORIGIN=http://localhost:8080
      - PORT=5000
    depends_on:
      - mongodb
    networks:
      - app-network

  web-console:
    build:
      context: ./Frontend/Centarlized Firewall Web Console
      dockerfile: dockerfile
    container_name: web-console
    ports:
      - "8080:80"
    depends_on:
      - firewall-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local